name: LLHL - Full Package Release (Development)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: 18
    
    - name: Install dependencies for Linux
      run: |
        make init-linux
      
    - name: Build LLHL proyect (Linux) with node-amxxpack
      run: |
        make build-linux
    
    - name: Rename dist folder
      run: |
        mv dist dist-linux
    
    - name: Install dependencies for Windows
      run: |
        make init-windows
    
    - name: Build LLHL proyect (Windows) with node-amxxpack
      run: |
        make build-windows

    - name: Download latest AMX Mod X 1.9
      run: |
        wget "https://www.amxmodx.org/latest.php?version=1.9&os=linux&package=base" -O amxx-linux.tar.gz
        wget "https://www.amxmodx.org/latest.php?version=1.9&os=windows&package=base" -O amxx-windows.zip
        tar -xzf amxx-linux.tar.gz -C dist-linux/ag
        unzip amxx-windows.zip -d dist/ag

    - name: Upload llhl-dev package for Linux
      uses: actions/upload-artifact@master
      with:
        name: llhl-dev-linux
        path: dist-linux
    
    - name: Upload llhl-dev package for Windows
      uses: actions/upload-artifact@master
      with:
        name: llhl-dev-windows
        path: dist