name: LLHL - Full Package Release (Development)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: Install dependencies for Linux
      run: |
        make init-linux
      
    - name: Build LLHL proyect (Linux) with node-amxxpack
      run: |
        make build-linux
