name: LLHL - Full Package Release (Development)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: 18
    
    - name: Install dependencies for Linux
      run: |
        make init-linux
      
    - name: Build LLHL proyect with node-amxxpack
      run: |
        make build-linux

    - name: Download latest AMX Mod X 1.9
      run: |
        wget "https://www.amxmodx.org/latest.php?version=1.9&os=linux&package=base" -O amxx.tar.gz
        tar -xzf amxx.tar.gz -C dist/ag

    - name: Upload llhl-dev package for Linux
      uses: actions/upload-artifact@master
      with:
        name: llhl-dev-linux
        path: dist