name: LLHL - Full Package Release (Development)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Download latest AMX Mod X 1.9
      run: |
        wget "https://www.amxmodx.org/latest.php?version=1.9&os=linux&package=base" -O amxx-linux.tar.gz
        wget "https://www.amxmodx.org/latest.php?version=1.9&os=windows&package=base" -O amxx-windows.zip
        mkdir amxx-windows amxx-linux
        tar -xzf amxx-linux.tar.gz -C amxx-linux
        unzip amxx-windows.zip -d amxx-windows

    - name: Download Metamod v1.21.1-am
      run: |
        wget "https://www.amxmodx.org/release/metamod-1.21.1-am.zip" -O metamod.zip
        unzip -j metamod.zip -x '*.dylib' -d metamod

    - name: Create LLHL folder structure for Windows and Linux
      run: |
        os=("llhl-dev-linux" "llhl-dev-windows")
        for i in "${os[@]}"
        do
          mkdir $i && cd $i && mkdir ag && cd ag
          mkdir addons gamemodes gfx locs maps models sound sprites

          # Return to the initial location
          cd $GITHUB_WORKSPACE
        done
    
    - name: Clone LLHL Resources Repository
      run: |
        git clone https://github.com/FlyingCat-X/llhl-resources.git
    
    - name: Copy neccesary files for compiling LLHL
      run: |
        # Copy amxmodx addons folder (Windows and linux)
        cp -a amxx-linux/addons/* llhl-dev-linux/ag/addons
        cp -a amxx-windows/addons/* llhl-dev-windows/ag/addons

        # Prepare for gRIP use
        cp llhl-resources/amxx-related/gRIP/include/*.inc ag/addons/amxmodx/scripting/include

        # Prepare for cURL use
        cp llhl-resources/amxx-related/curl-1.1.1/include/*.inc ag/addons/amxmodx/scripting/include

        # In case the repository has an include folder, we copy the dependencies
        if [ -d ag/addons/amxmodx/scripting/include ]; then
          echo "Copying non-standard dependencies..."
          cp -a ag/addons/amxmodx/scripting/include/*.inc amxx-linux/addons/amxmodx/scripting/include
        fi

        # Add missing native is_user_authorized (amxmodx.inc)
        sed 's/native is_user_hltv(index);/& \nnative is_user_authorized(index);\n/' amxx-linux/addons/amxmodx/scripting/include/amxmodx.inc -i

    - name: Compile LLHL plugin
      run: |
        # Move to the folder where the compiler is located
        cd amxx-linux/addons/amxmodx/scripting

        # Give amxxpc the required permissions
        chmod +x amxxpc

        # Compile all plugins inside scripting folder
        for file in $GITHUB_WORKSPACE/ag/addons/amxmodx/scripting/*.sma
        do
          smafile="`echo $file | sed -e 's/\.sma$/\.amxx/'`"
          echo -e "\nCompiling $(basename $file)..." 
          ./amxxpc $file -o$GITHUB_WORKSPACE/llhl-dev-linux/ag/addons/amxmodx/plugins/$(basename "$smafile")
        done

        # Returning to the initial location
        cd $GITHUB_WORKSPACE

        # Copy compiled plugins to windows artifact
        cp -a llhl-dev-linux/ag/addons/amxmodx/plugins/*.amxx llhl-dev-windows/ag/addons/amxmodx/plugins

    - name: Copy the rest of the files
      run: |
        os=("llhl-dev-linux" "llhl-dev-windows")
        for systems in "${os[@]}"
        do
          # Copy llhl plugins list and multilanguage files
          cp ag/addons/amxmodx/data/lang/*.txt $systems/ag/addons/amxmodx/data/lang
          cp ag/addons/amxmodx/configs/plugins-llhl.ini $systems/ag/addons/amxmodx/configs

          # Copy the rest of the directories and files from llhl repo
          toCopy=("gamemodes" "sound" "motd_llhl.txt" "startup_server.cfg")
          for tc in "${toCopy[@]}"
          do
            # Directory
            if [[ -d ag/$tc ]]; then
              cp -a ag/$tc/* $systems/ag/$tc
            # File
            elif [[ -f ag/$tc ]]; then
              cp -a ag/$tc $systems/ag
            fi
          done
        done

        # Copy resources (Maps, locs, wads, etc)
        for systems in "${os[@]}"
        do
          # Resources to copy
          resourcesToCopy=("maps-ag-official" "maps-ehll-unofficial" "maps-valve-official")
          for rtc in "${resourcesToCopy[@]}"
          do
            # Directory
            if [[ -d llhl-resources/$rtc ]]; then
              cp -a llhl-resources/$rtc/* $systems/ag
            # File
            elif [[ -f llhl-resources/$rtc ]]; then
              cp -a llhl-resources/$rtc $systems/ag
            fi
          done
        done

        # Create metamod folder and copy metamod plugin
        mkdir llhl-dev-linux/ag/addons/metamod llhl-dev-linux/ag/addons/metamod/dlls
        mkdir llhl-dev-windows/ag/addons/metamod llhl-dev-windows/ag/addons/metamod/dlls
        cp metamod/*.so llhl-dev-linux/ag/addons/metamod/dlls
        cp metamod/*.dll llhl-dev-windows/ag/addons/metamod/dlls

        # Copy GhostMineBlock to metamod plugins folder
        cp llhl-resources/metamod-plugins/ghostmineblock-1.5/*.so llhl-dev-linux/ag/addons/metamod/dlls
        cp llhl-resources/metamod-plugins/ghostmineblock-1.5/*.dll llhl-dev-windows/ag/addons/metamod/dlls

        # Copy gRIP Module to amxmodx modules folder
        cp llhl-resources/amxx-related/gRIP/module/*.so llhl-dev-linux/ag/addons/amxmodx/modules
        cp llhl-resources/amxx-related/gRIP/module/*.dll llhl-dev-windows/ag/addons/amxmodx/modules
        cp llhl-resources/amxx-related/gRIP/configs/*.ini llhl-dev-linux/ag/addons/amxmodx/configs
        cp llhl-resources/amxx-related/gRIP/configs/*.ini llhl-dev-windows/ag/addons/amxmodx/configs

        # Copy cURL Module to amxmodx modules folder
        cp llhl-resources/amxx-related/curl-1.1.1/module/*.so llhl-dev-linux/ag/addons/amxmodx/modules
        cp llhl-resources/amxx-related/curl-1.1.1/module/*.dll llhl-dev-windows/ag/addons/amxmodx/modules

        # Add amxmodx to metamod plugins
        metamodPluginsLinux+='\nlinux addons/metamod/dlls/gm_block_mm_i386.so'
        metamodPluginsLinux+='\nlinux addons/amxmodx/dlls/amxmodx_mm_i386.so'

        metamodPluginsWin+='\nwin32 addons/metamod/dlls/gm_block_mm.dll'
        metamodPluginsWin+='\nwin32 addons/amxmodx/dlls/amxmodx_mm.dll'

        echo -e $metamodPluginsLinux > llhl-dev-linux/ag/addons/metamod/plugins.ini
        echo -e $metamodPluginsWin > llhl-dev-windows/ag/addons/metamod/plugins.ini

        liblist='// Valve Game Info file'
        liblist+='\n// These are key/value pairs.  Certain mods will use different settings.'
        liblist+='\ngame "Adrenaline Gamer Steam"'
        liblist+='\nurl_info "http://half-life.pro"'
        liblist+='\nurl_dl ""'
        liblist+='\nversion "6.6"'
        liblist+='\nsize "93961341"'
        liblist+='\nsvonly "0"'
        liblist+='\ntype "multiplayer_only"'
        liblist+='\ncldll "0"'
        liblist+='\nmpentity "info_player_deathmatch"'
        liblist+='\ngamedll "addons\metamod\dlls\metamod.dll"'
        liblist+='\ngamedll_linux "addons/metamod/dlls/metamod.so"'
        liblist+='\ngamedll_osx "dlls/hl.dylib"'
        liblist+='\nsecure "1"'
        liblist+='\ncrcclientdll "1"'

        # Create liblist.gam file
        echo -e $liblist > llhl-dev-linux/ag/liblist.gam
        echo -e $liblist > llhl-dev-windows/ag/liblist.gam

        # Remove unnecessary folders
        rm -r llhl-dev-linux/ag/addons/amxmodx/scripting
        rm -r llhl-dev-windows/ag/addons/amxmodx/scripting

    - name: Upload llhl-dev package for Linux
      uses: actions/upload-artifact@master
      with:
        name: llhl-dev-linux
        path: llhl-dev-linux

    - name: Upload llhl-dev package for Windows
      uses: actions/upload-artifact@master
      with:
        name: llhl-dev-windows
        path: llhl-dev-windows
